server:
  port: 8081

spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false


  datasource:
    # MySQL
    url: jdbc:mysql://localhost:3315/spring_boot
    username: user
    password: password
    ## connectionProperties: useUnicode=true&characterEncoding=UTF-8&serverTimezone=JST
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      connection-properties: useUnicode=true&characterEncoding=UTF-8&serverTimezone=JST

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # MySQL
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    root: warn
    # org.springframewordk.web : warn
    com.ds: warn
  file: logs/debug.log